# Generated by Django 5.2.5 on 2025-08-28 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the world/campaign', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description of the world/universe')),
                ('join_code', models.CharField(blank=True, help_text='Unique code for sharing world access', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether world is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='World creator/DM', on_delete=django.db.models.deletion.CASCADE, related_name='owned_worlds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'World',
                'verbose_name_plural': 'Worlds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description of the category')),
                ('sort_order', models.IntegerField(default=0, help_text='Order within parent category')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide category from non-authors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category')),
                ('world', models.ForeignKey(help_text='World this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.world')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('world', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorldUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('co_creator', 'Co-Creator'), ('player', 'Player')], help_text='User role in this world', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_memberships', to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_users', to='core.world')),
            ],
            options={
                'verbose_name': 'World User',
                'verbose_name_plural': 'World Users',
                'ordering': ['-joined_at'],
                'unique_together': {('world', 'user')},
            },
        ),
    ]
