# Generated by Django 5.2.5 on 2025-08-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='theme_color',
            field=models.CharField(default='#8b7355', help_text='Theme color for the world card', max_length=20),
        ),
    ]
