# Generated by Django 5.2.5 on 2025-08-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_world_theme_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('world', 'parent', 'name')},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name', max_length=255),
        ),
        migrations.AddField(
            model_name='world',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('world', 'parent', 'name'), ('world', 'parent', 'slug')},
        ),
    ]
