# Generated by Django 4.2.7 on 2025-08-22 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('book_type', models.CharField(choices=[('world', 'World Book'), ('adventurer', "Adventurer's Book"), ('story', 'Story Book')], max_length=20)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_categories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='books.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('book_type', models.CharField(choices=[('world', 'World Book'), ('adventurer', "Adventurer's Book"), ('story', 'Story Book')], max_length=20)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='books.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HiddenTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('start_position', models.IntegerField(help_text='Character position where hidden content starts')),
                ('end_position', models.IntegerField(help_text='Character position where hidden content ends')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_blocks', to='books.entry')),
            ],
            options={
                'ordering': ['start_position'],
            },
        ),
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Description of the reference', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_references', to='books.entry')),
                ('target_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_references', to='books.entry')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('source_entry', 'target_entry')},
            },
        ),
    ]
